import { RestaurantInterface } from '@/interfaces/restaurant';

export const mockRestaurants: RestaurantInterface[] = [
  {
    id: 1,
    name: 'Matsuri Concept',
    rating: 4.7,
    image: '/images/matsuri.png',
    deliveryFee: 0,
    minimumOrderPrice: 15,
    estimatedDeliveryTime: { min: 30, max: 40 },
    distance: 5.2,
    closingTime: '20:00',
    openingTime: '18:00',
    isOpen: true,
    maxValueDeliveryFee: 0
  },
  {
    id: 2,
    name: 'Subway Avenida Center',
    rating: 4.4,
    image: '/images/subway.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 40, max: 50 },
    distance: 28,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: true,
    maxValueDeliveryFee: 0
  },
  {
    id: 3,
    name: 'Burger King Colombo',
    rating: 5,
    image: '/images/burguerking.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 60, max: 70 },
    distance: 12,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: true,
    maxValueDeliveryFee: 0
  },
  {
    id: 4,
    name: 'Burger King Colombo',
    rating: 5,
    image: '/images/burguerking.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 60, max: 70 },
    distance: 12,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: true,
    maxValueDeliveryFee: 0
  },
  {
    id: 5,
    name: 'Matsuri Concept',
    rating: 4.7,
    image: '/images/matsuri.png',
    deliveryFee: 0,
    minimumOrderPrice: 15,
    estimatedDeliveryTime: { min: 30, max: 40 },
    distance: 5.2,
    closingTime: '20:00',
    openingTime: '18:00',
    isOpen: false,
    maxValueDeliveryFee: 0
  },
  {
    id: 6,
    name: 'Subway Avenida Center',
    rating: 4.4,
    image: '/images/subway.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 40, max: 50 },
    distance: 28,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: false,
    maxValueDeliveryFee: 0
  },
  {
    id: 7,
    name: 'Burger King Colombo',
    rating: 5,
    image: '/images/burguerking.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 60, max: 70 },
    distance: 12,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: false,
    maxValueDeliveryFee: 0
  },
  {
    id: 8,
    name: 'Burger King Colombo',
    rating: 5,
    image: '/images/burguerking.png',
    deliveryFee: 6,
    minimumOrderPrice: 32,
    estimatedDeliveryTime: { min: 60, max: 70 },
    distance: 12,
    closingTime: '23:59',
    openingTime: '18:00',
    isOpen: false,
    maxValueDeliveryFee: 0
  }
];
